config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  # Projects index action
  get '/projects', to: 'projects#index'
  # Skills index action
  get '/about', to: 'skills#index'
  
end

app/models/point.rb
class Point < ActiveRecord::Base
  
  belongs_to :project
  
  validates :body, presence: true, length: { minimum: 5, maximum: 130 }
  
end

app/models/project.rb
class Project < ActiveRecord::Base
  
  has_many :points, dependent: :destroy
  
  validates :title, presence: true, length: { in: 2..22 }
  validates :description, presence: true, length: { in: 2..120 }
  validates :git_link, length: { in: 5..100 }
  validates :live_link, length: { in: 5..100 }
  validates :image, presence: true
  validates :category, presence: true, length: {in: 2..60}, format: { with: /\A[a-zA-Z .,]+\z/,
    message: "only allows letters, spaces, periods, and commas" }
  
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  
  validates :skill, presence: true, length: {minimum: 1, maximum: 35 }
  validates :rating, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  include SkillsHelper
  
  def home
    @top_skills = top_skills
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  include ProjectsHelper

  def index
    if params[:project_type]
      assign_projects(project_params)
    else
      @projects = Project.all.reverse
    end
  end

  private

    def project_params
      params.require(:project_type)
    end
  
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

  include SkillsHelper

  def index
    categorize_skills
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def assign_projects(project_type)
    if project_type == 'Sinatra'
      @projects = Project.where("category LIKE ?", '%Sinatra%').reverse

    elsif project_type == 'Ruby on Rails'
      @projects = Project.where("category LIKE ?", '%Rails%').reverse

    elsif project_type == 'Unity3D'
      @projects = Project.where("category LIKE ?", '%Unity%').reverse

    else
      params[:project_type] = nil
      @projects = Project.all.reverse

    end
  end

end

app/helpers/skills_helper.rb
module SkillsHelper

  def top_skills
    skill_names = ["Ruby on Rails", "React Native.js", "JavaScript", "Ruby", "Node.js", "PostgreSQL", "REST APIs", "HTML5", "Sinatra", "Git"]

    skill_names.map do |name|
      Skill.find_by(skill: name)
    end
  end

  

  def gen_stars(rating)

    if rating === 2
      stars = "&#9734; " * 2

    elsif rating === 3
      stars = "&#9734; " * 3

    elsif rating === 4
      stars = "&#9734; " * 4

    elsif rating === 5
      stars = "&#9734; " * 5

    else
      stars = "N/A"
    end

    stars.html_safe

  end



  def categorize_skills
    @languages, @frameworks, @libraries, @databases, @other = [], [], [], [], []

    Skill.all.each do |skill| 
      p skill

      if skill.skill_type == "Languages"
        @languages.push(skill)

      elsif skill.skill_type == "Frameworks"
        @frameworks.push(skill)

      elsif skill.skill_type == "Libraries"
        @libraries.push(skill)

      elsif skill.skill_type == "Databases"
        @databases.push(skill)

      else
        @other.push(skill)
        
      end
    end
  end

end

app/views/layouts/_footer.html.erb
<footer class="page-footer light-blue darken-2">
  <div class="container">
    <div class="row">
      
      <div class="col s12 center">

        <p><%= link_to "Projects", projects_path, class: "white-text" %> | <%= link_to "About Me", about_path, class: "white-text" %></p>
        
        <%= link_to "https://github.com/nitescun" do %>
          <i class="fa fa-github fa-2x"></i>
        <% end %>
        
        <!--Pipe Separator-->
         | 
        
        <!--Facebook Link-->
        <%= link_to 'https://www.facebook.com/nicolae.nitescu.5' do %>
          <i class="fa fa-facebook fa-2x"></i>
        <% end %>
        
        <!--Pipe Separator-->
         | 
        
        <!--Linkedin Link-->
        <%= link_to 'https://www.linkedin.com/in/nicolae-nitescu-30596455' do %>
          <i class="fa fa-linkedin fa-2x"></i>
        <% end %>
        
        <!--Pipe Separator-->
         | 
         
        <!--Linkedin Link-->
        <%= mail_to 'nicolaen@gmail.com' do %>
          <i class="fa fa-envelope fa-2x" aria-hidden="true"></i>
        <% end %>
        
      </div>
    </div>
  </div>
  <div class="footer-copyright light-blue darken-4 center">
    <div class="container">
      Copyright &copy; 2016. Portfolio of Nicolae Nitescu.
    </div>
  </div>
</footer>

app/views/layouts/_head.html.erb
<title>Nicolae - Full Stack Web Developer</title>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

<!--Import Google Fonts-->
<link href='https://fonts.googleapis.com/css?family=Aldrich' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet' type='text/css'>

<!--Import Font Awesome Icons-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

<!-- Material Icons -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<!--Let browser know website is optimized for mobile-->
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>

<%= csrf_meta_tags %>

<!--Site Description for SEO-->
<meta name="description" content="Nicolae is a Full Stack Web Developer in San Francisco.
View his projects, video games, or his competencies here.">

<link rel="icon" href="assets/images/N2-Favicon.png">

app/views/layouts/_nav.html.erb
<nav>
  <div class="nav-wrapper light-blue lighten-2">
    <%= link_to image_tag("N2-Logo-White-compressor.png", class: "kelsonic"), root_path, class: "brand-logo center" %>
    <a class="button-collapse" data-activates="mobile-demo" href="#"><i class="fa fa-bars">Think beautiful</i></a>
    <ul class="right hide-on-med-and-down">
      <li><%= link_to "Projects", projects_path %></li>
      <li><%= link_to "About Me", about_path %></li>
    </ul>
    <ul id="mobile-demo" class="side-nav" style="left: -250px;">
      <li><%= link_to "Projects", projects_path %></li>
      <li><%= link_to "About Me", about_path %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <%= render 'layouts/head' %>
  
</head>
<body>
  
  <header>
    <%= render 'layouts/nav' %>
  </header>
  
  <main>
    <%= yield %>
  </main>
  
  <%= render 'layouts/footer' %>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>

app/views/pages/home.html.erb
<div id="index-banner" class="parallax-container">
  <div class="section no-pad-bot">
    <div class="container black-bg col s12 m8 offset-m2 l4 offset-l4">
      <div class="row center">

        <h1 class="center grey-text text-lighten-2 kelsonic">Nicolae Nitescu</h1>

        <%= image_tag("profile_compressed.jpg", alt: "Kelsonic.io", class: "img-container responsive-img") %>

        <h5 class="header white-text">Full-Stack Web Developer</h5>

      </div>
      <div class="row center">
        <%= link_to "Portfolio", projects_path, id: "download-button", class: "btn-large waves-effect waves-light orange lighten-1" %>
      </div>
    </div>
  </div>
  <div class="parallax"><%= image_tag("home.jpg", alt: "Placeholder image", class: "responsive-img") %></div>
</div>

<div class="divider light-blue"></div>

<div class="row center">
  <div class="col s12">
    <h3 class="light-blue-text text-darken-4">Top Competencies</h3>
  </div>
</div>

<!--Skills Card-->
<div class="row">
  <div class="col s12 m8 offset-m2">
    <div class="card orange">
      <div class="card-content white-text">
        <table class="highlight centered">
          <thead>
            <tr>
              <th>Skill</th>
              <th>rating</th>
            </tr>
          </thead>

          <tbody>
            <% @top_skills.each do |skill| %>
              <tr>
                <td><%= skill.skill %></td>
                <td><%= gen_stars(skill.rating) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="row center">
  <div class="col s12">
    <h3 class="blue-text text-darken-4">Want to see all of my competencies?</h3>
    <br/>
    <%= link_to "Yes, take me there", about_path, class: "btn btn-large light-blue waves-effect waves-orange" %>
  </div>
</div>

app/views/projects/_filter_projects.html.erb
<div class="row center">
  <% if params[:project_type] %>
    <%= link_to "View All Projects", projects_path, class: "orange-text text-darken-2" %>
    <br /><br />
  <% end %>

  <%= link_to "Sinatra", projects_path(project_type: 'Sinatra') %>
  | <%= link_to "Ruby on Rails", projects_path(project_type: 'Ruby on Rails') %>
  | <%= link_to "Unity3D Games", projects_path(project_type: 'Unity3D') %>
</div>

app/views/projects/_header.html.erb
<div class="center">
  <h2 class="orange-text text-darken-2">
    My <span class="light-blue-text"><%= params[:project_type] if params[:project_type] %></span> Projects
  </h2>
  <p class="grey-text">
    I created the following projects by consulting countless online references,
    online bootcamps, actual bootcamps, and many books.
  </p>
  <p class="grey-text text-darken-1">
    Filter Projects by Technology
  </p>
</div>

app/views/projects/_project.html.erb
<div class="row">
  <div class="col s12">
    <div class="col s12 l6 center">

      <a href="<%= project.live_link %>"><h2 class="project-header blue-text"><%= project.title %></h2></a>
      <p class="technology orange-text">(<span class="grey-text text-darken-3"><%= project.category %></span>)</p>

      <br/>

      <ul class="collapsible left-align" data-collapsible="accordion">
        <li>
          <div class="collapsible-header orange-text"><i class="fa fa-rocket grey-text text-darken-3" aria-hidden="true"></i> Launch Date</div>
          <div class="collapsible-body grey darken-3 white-text"><p><%= project.launched.strftime('%B, %Y') %></p></div>
        </li>
        <li>
          <div class="collapsible-header orange-text"><i class="fa fa-info-circle grey-text text-darken-3" aria-hidden="true"></i> Description</div>
          <div class="collapsible-body grey darken-3 white-text"><p><%= project.description %></p></div>
        </li>
        <li>
          <div class="collapsible-header orange-text"><i class="fa fa-bars grey-text text-darken-3" aria-hidden="true"></i> Details</div>
          <div class="collapsible-body grey darken-3 white-text">
            <% project.points.each do |point| %>
              <p><%= point.body %></p>
            <% end %>
          </div>
        </li>
      </ul>

      <br/>

    </div>

    <div class="col s12 l6">
      <%= link_to image_tag(project.image, class: "responsive-img"), project.live_link, target: "_blank" %>
      <p class="flow-text center"><i class="fa fa-github black-text"></i> <%= link_to "GitHub Repository", project.git_link, class: "blue-text" %></p>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div class="container">
  <div class="section">

    <!--   Icon Section   -->
    <div class="row">
      <div class="col s12">
        <div class="icon-block">
          
          <!--Header portfolio-->
          <%= render 'header' %>
          
          <!-- Filter project category buttons   -->
          <%= render 'filter_projects' %>
          
          <!-- Projects -->
          <% @projects.each do |project| %>
            <hr/>
            <br/>
            <%= render 'project', project: project %>
          <% end %>

          <%= render 'filter_projects' %>
          
        </div>
      </div>
    </div>
  </div>
</div>

app/views/skills/_intro_card.html.erb
<div class="row">
  <div class="col s12 m10 offset-m1 l8 offset-l2">
    <div class="card orange">
      <div class="card-content white-text">
        <div class="card-title center">
          Nice to meet you!
        </div>
        <p>
          My name is Nicolae. I am a full stack web developer living in Sunnyvale, Ca. I like to travel
          and my favorite place is Kings Canyon.
          Apart from programming languages, I speak English, Romanian,
          and a little French.
        </p>
        <br/>
        <div class="center">
          <p class="flow-text">Click the images to learn more about me.</p>
          <br/>
          <p>Otherwise, you can also view my</p>
          <p class="flow-text">competencies below.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/skills/_location.html.erb
<div class="col s12 m6">
  <div class="card orange">
    <div class="card-image waves-effect waves-block waves-light">
      <%= image_tag(image, class: "activator") %>
    </div>
    <div class="card-content white-text">
      <span class="card-title activator">
        <%= location %><i class="fa fa-ellipsis-v right"></i>
      </span>
      <p><%= years %></p>
    </div>
    <div class="card-reveal light-blue">
      <span class="card-title white-text">
        <%= location %><i class="fa fa-times-circle right"></i>
      </span>
      <p class="white-text">
        <%= para1 %>
      </p>
      <p class="white-text">
        <%= para2 %>
      </p>
      <p class="white-text">
        <%= para3.html_safe %>
      </p>
    </div>
  </div>
</div>

app/views/skills/_skill_type.html.erb
<!--Skill Table-->
<div class="row">
  <div class="col s12 m10 offset-m1 l8 offset-l2" id="<%= skills.first.skill_type.downcase %>">
    <div class="card orange">
      <div class="card-content white-text">
        <div class="card-title center">
          <%= skills.first.skill_type %>
        </div>
        <table class="highlight centered">
          <thead>
            <tr>
              <th>Skill</th>
              <th>Proficiency</th>
            </tr>
          </thead>

          <tbody>
            <% skills.each do |skill| %>
              <tr>
                <td><%= skill.skill %></td>
                <td><%= gen_stars(skill.rating) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/skills/index.html.erb
<section class="blog-font">

  <!--Intro Card-->
  <%= render 'intro_card' %>

  <!--Cards-->
  <!-- Start Row -->
  <div class="row">

    <!--Colorado-->
    <%= render 'location',
      image: 'Romania.JPG',
      location: 'Romania',
      years: '',
      para1: "I am Nicolae. I was born and raised in Romania. I spent all my
            vacations reading and writing books, hiking in the Carpathians,
            playing soccer and tennis. At 14 I discovered the computers and I
            started  coding so that I can produce my own games.",
      para2: "I have always been interested in exploring organizational systems
            and perspectives available worldwide and been appreciative of
            education beyond the classroom.",
      para3: "One day, I have been offered an assignment in the US. I packed my
            bags right away and got ready to face the new experience heads-on."
    %>

    <!--Italy-->
    <%= render 'location',
      image: 'US.JPG',
      location: 'US',
      years: '',
      para1: "I moved to Sunnyvale, California and worked with integrated
            circuits for some time, building programs that automatically design
            them. Work left aside, I travelled a lot, especially during the
            weekends. This way I discovered many beautiful places in California
            and in the neighboring states. Nature has always helped me focus and
             shape the ideas that I work on at different times.",
      para2: "Also, I have built  my first personal computer in Sunnyvale.
            Because I enjoyed the experience and totally loved the final
            product, I kept this habit over the years and I continue building my
             own machines today. Seldom buy.",
      para3: "While not programming for work, I took care of my own projects.
            In college the ANN concept was introduced to us and since then the
            subject became a personal passion and captures a lot of my personal
            time. Robots make for a material presence cross-industry today and
            they have quickly turned into the backbone of our economy. Moreover,
             progress is still happening and not before long, robots and AI
             systems will completely change the world as we know it."
    %>

  <!--End Row-->
  </div>


  <div class="row">

    <!--Netherlands-->
    <%= render 'location',
      image: 'Kings_Canyon.jpg',
      location: 'Kings Canyon',
      years: '',
      para1: "I discovered Kings Canyon National Park travelling around, in one
            of the many weekend outings. It immediately became
            my favorite place to camp.",
      para2: "At work I soon started to develop programs used in testing
            intergrated circuits. Always a fan of automation and of making things
             faster and less prone to error, with a minimum of effort, my
            coleagues joked on my using of automation everywhere.",
      para3: "I started researching the way that the human brain functions and
              after a while I got the idea of the program I am working on today.
             My AI application should be capable of learning by reading
             information on its own and by even freely talking with people, with
              a minimum of resources."
    %>

    <!--San Francisco-->
    <%= render 'location',
      image: 'sf.jpg',
      location: 'San Francisco',
      years: '',
      para1: "A big wish was to expand my knowledge so that I can come even
            closer to coding and developing applications so I slowly switched
            gears and this is how I started to work as a software QA engineer
            first. But that was obviously not enough for my goal so I ended up
            working though the Dev Bootcamp program in San Francisco. It turned
            out to be a good thing to do as it helped me to fill in a few gaps.",
      para2: "Dev Bootcamp meant coding around the clock, often 7 days a week.
            I pushed myself to accomplish at least one project per week, and it
            paid off. By the end of the program, I had built 20+ projects, most
            of them using different technologies, that I had to learn in only a
            couple of days or overnight.",
      para3: "The final project, that I built together with three other
            colleagues, is called Simul. Simul is an application designed to help
             the refugees. It allows them to share personal stories, find
             resources that they need, and get in contact with people that may
             and want to help them."
    %>

  <!-- End Row -->
  </div>

  <div class="row center">
    <div class="divider"></div>
    <br/>
    <h2 class="light-blue-text">My Competencies</h2>
  </div>

  <%= render 'skill_type', skills: @languages %>
  <%= render 'skill_type', skills: @frameworks %>
  <%= render 'skill_type', skills: @libraries %>
  <%= render 'skill_type', skills: @databases %>
  <%= render 'skill_type', skills: @other %>

  <div class="row center">
    <%= link_to "View Projects", projects_path, class: "btn btn-large light-green waves-effect waves-orange" %>
  </div>

</section>